name:                Day02
version:             0.1.0.0
github:              "DavidAntliff/AdventOfCode/2019/Day02"
license:             BSD3
author:              "David Antliff"
copyright:           "2019 David Antliff"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers

executables:
  part1:
    main:                Main.hs
    source-dirs:         part1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day02

  part2:
    main:                Main.hs
    source-dirs:         part2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day02

tests:
  test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - tasty
    - tasty-hunit
    - Day02
